INSERT INTO `doctor`(`name`) VALUES ('ADAM BERLIAN TRISNADI. dr');
INSERT INTO `doctor`(`name`) VALUES ('AFRIYANDI ISHAR. Dr');
INSERT INTO `doctor`(`name`) VALUES ('ARDENO KRISTIANTO, Dr');
INSERT INTO `doctor`(`name`) VALUES ('ARIBOWO, dr');
INSERT INTO `doctor`(`name`) VALUES ('BELLINA FEBRIANING SUKMA, Dr');
INSERT INTO `doctor`(`name`) VALUES ('EVI ANDANI, dr');
INSERT INTO `doctor`(`name`) VALUES ('HERMIN WIDYAPRASTUTI, Dr');
INSERT INTO `doctor`(`name`) VALUES ('HUTOMO. Dr');
INSERT INTO `doctor`(`name`) VALUES ('JANE CHERUB, Dr');
INSERT INTO `doctor`(`name`) VALUES ('JEANNY SUSANTO, dr');
INSERT INTO `doctor`(`name`) VALUES ('KEN ARIATA, Dr');
INSERT INTO `doctor`(`name`) VALUES ('LENNY SETIAWATI, Dr');
INSERT INTO `doctor`(`name`) VALUES ('LENY SILVIA RAHAYU, dr');
INSERT INTO `doctor`(`name`) VALUES ('RICKY SUWANDI, dr. MM, MARS');
INSERT INTO `doctor`(`name`) VALUES ('ROKANITA WIDAYANTO, Dr');
INSERT INTO `doctor`(`name`) VALUES ('RUDY, dr');
INSERT INTO `doctor`(`name`) VALUES ('SUWANDY HB, dr');
INSERT INTO `doctor`(`name`) VALUES ('SUWOTO, dr');
INSERT INTO `doctor`(`name`) VALUES ('VIRGINIA SEPTIANI, Dr');
INSERT INTO `doctor`(`name`) VALUES ('YOHANES AGUNG PUTRA,Dr');
INSERT INTO `doctor`(`name`) VALUES ('NANCY R SUPRIYANTO, Dr');
INSERT INTO `doctor`(`name`) VALUES ('MEIYANTI BUDIANI, Dr');
INSERT INTO `doctor`(`name`) VALUES ('CAROLINE DEWI. Dr');
INSERT INTO `doctor`(`name`) VALUES ('MARGARETHA SYANE, dr');