INSERT INTO `nurse`(`name`) VALUES ('Sr. Nurhayati Kasbi');    
INSERT INTO `nurse`(`name`) VALUES ('Sr. Siti Komariah');  
INSERT INTO `nurse`(`name`) VALUES ('Sr. Astuti Rahmah');     
INSERT INTO `nurse`(`name`) VALUES ('Sr. Nurwidiasih');  
INSERT INTO `nurse`(`name`) VALUES ('Sr. Bunga Wulandari');    
INSERT INTO `nurse`(`name`) VALUES ('Sr. Ine Dwi Tantias');    
INSERT INTO `nurse`(`name`) VALUES ('Sr. Noviyanti');       
INSERT INTO `nurse`(`name`) VALUES ('Sr. Artatina Lase');       
INSERT INTO `nurse`(`name`) VALUES ('Sr. Anggraini Titias A');  
INSERT INTO `nurse`(`name`) VALUES ('Sr. Esterlyna O');
INSERT INTO `nurse`(`name`) VALUES ('Sr. Atika');      
INSERT INTO `nurse`(`name`) VALUES ('Sr. Henny Widyanti');      
INSERT INTO `nurse`(`name`) VALUES ('Sr. Septi');   
INSERT INTO `nurse`(`name`) VALUES ('Sr. Morinain Vrischa');  
INSERT INTO `nurse`(`name`) VALUES ('Sr. Gusnelly Lidia'); 
INSERT INTO `nurse`(`name`) VALUES ('Sr. Denita B.P');   
INSERT INTO `nurse`(`name`) VALUES ('Sr. Peggy');          
INSERT INTO `nurse`(`name`) VALUES ('Sr. Fajar Ayu');           
INSERT INTO `nurse`(`name`) VALUES ('Sr. Niken Tri');        
INSERT INTO `nurse`(`name`) VALUES ('Sr. Rosalia F');        
INSERT INTO `nurse`(`name`) VALUES ('Sr. Retno Dwi');       
INSERT INTO `nurse`(`name`) VALUES ('Sr. Dewi Sekar');        